export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'NEW_POST';
export const GET_USERS = 'GET_USERS';
export const GET_TIPPCARDS = 'GET_TIPPCARDS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_INTERACTIONS = 'GET_INTERACTIONS';
export const GET_USERTIPPCARDS = 'GET_USERTIPPCARDS';
export const GET_KINDS = 'GET_KINDS';

